name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run clippy
      run: |
        nix develop --command cargo clippy --all-targets --all-features -- -D warnings

    - name: Run build
      run: |
        nix develop --command cargo build --verbose

    - name: Run tests
      run: |
        nix develop --command cargo test --verbose

    - name: Run fmt
      run: |
        nix develop --command cargo fmt --check

  python:
    name: Python lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint
      run: |
        cd python && nix develop --command make lint

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Nix package
      run: |
        nix build

  all-required-checks-complete:
    if: ${{ always() }}
    needs: [nix-build, rust, python]
    runs-on: ubuntu-latest
    steps:
      - uses: G-Research/common-actions/check-required-lite@2b7dc49cb14f3344fbe6019c14a31165e258c059
        with:
          needs-context: ${{ toJSON(needs) }}
